def answerEntity(item) -> dict:
    return{
        "id": str(item["_id"]),
        "firm": item["firm"],
        "date": item["date"],
        "rec1": item["rec1"],
        "rec2": item["rec2"],
        "rec3": item["rec3"],
        "rec4": item["rec4"],
        "rec5": item["rec5"],
        "arm1": item["arm1"],
        "arm2": item["arm2"],
        "arm3": item["arm3"],
        "ent1": item["ent1"],
        "ent2": item["ent2"],
        "ent3": item["ent3"],
        "ent4": item["ent4"],
        "ent5": item["ent5"],
        "exp1": item["exp1"],
        "exp2": item["exp2"],
        "exp3": item["exp3"],
        "ins1": item["ins1"],
        "ins2": item["ins2"],
        "ins3": item["ins3"],
        "com1": item["com1"],
        "com2": item["com2"],
        "com3": item["com3"],
        "aca1": item["aca1"],
        "aca2": item["aca2"],
        "aca3": item["aca3"],
        "inf1": item["inf1"],
        "inf2": item["inf2"],
        "inf3": item["inf3"],
        "inf4": item["inf4"],
        "int1": item["int1"],
        "int2": item["int2"],
        "int3": item["int3"],
        "dad1": item["dad1"],
        "dad2": item["dad2"],
        "dad3": item["dad3"]
    }


def answersEntity(entity) -> list:
    return [answerEntity(item) for item in entity]
